### ISSUE TITLE
ERROR:/im2txt/bazel-bin/im2txt/run_inference: No such file or directory

### ISSUE THREAD

**Issue by jmfu95** [siavash9000/im2txt_demo#6]
when i  type "./process_image.sh imgs/bikes.jpg",i got this below.
Processing imgs/bikes.jpg
./process_image.sh: line 21: /im2txt/bazel-bin/im2txt/run_inference: No such file or directory

so please kindly tell me why and how to solve it?
thank you!
@siavash9000 @mmattozzi @valentinvieriu

**Comment by mmattozzi** [comment]
Did you run `./build_inference.sh` inside of the docker container after it started up? What were the results of the bazel build script?

**Comment by jmfu95** [comment]
root@5e09614cd55f:~# ./build_inference.sh
INFO: Analysed target //im2txt:run_inference (0 packages loaded).
INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  bazel-bin/im2txt/run_inference
INFO: Elapsed time: 0.246s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
/root

**Comment by jmfu95** [comment]
Then i type  i./process_image.sh imgs/bikes.jpg,it occurs the error  below.too much error.this is part 
DataLossError (see above for traceback): Unable to open table file /root/im2txt_pretrained/model.ckpt-2000000: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_337 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_337/tensor_names, save/RestoreV2_337/shape_and_slices)]]

**Comment by mmattozzi** [comment]
Did you download the model from the link on the README page? Here's the size and md5 of the model I'm using: 

```
$ ls -lh model.ckpt-2000000
-rw-r--r--  1 mmattozzi  staff   142M Jul 20 15:02 model.ckpt-2000000
$ md5 model.ckpt-2000000
MD5 (model.ckpt-2000000) = 829c72e48635db15bb147a848bb3069d
```

You should only replace `model.ckpt-2000000` in the `im2txt_pretrained` directory, nothing else.

**Comment by jmfu95** [comment]
Thank you very much.It worked.

**Comment by jmfu95** [comment]
But it still has this problem...sad
root@5e09614cd55f:~# ./process_image.sh imgs/bike.jpg
Processing imgs/bike.jpg
WARNING:tensorflow:From /root/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/ops/image_processing.py:95 in image_summary.: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.

**Comment by siavash9000** [comment]
This just a warning due to the old tensorflow version of this project. The main output of the inference can be found at the end:
```
Captions for ...
0) ...
1) ...
3) ...
```

**Comment by jmfu95** [comment]
@siavash9000 Thank you for your reply.
But i am sorry ,i did not have found the correct output.It still have problems and i don't know where is wrong.

`root@a6051198dfe2:~# ./process_image.sh imgs/bike.jpg
Processing imgs/bike.jpg
WARNING:tensorflow:From /root/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/ops/image_processing.py:95 in image_summary.: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
`

**Comment by siavash9000** [comment]
ok, thats strange. Do you let the command run to the end? I rebuild everything and tried to reproduce your problem. I get also deprecation warnings, but also the correct prediction in the end. 
What is your docker version? 

My output looks like the folowing. You can see the prediction in the end:

```
root@eeb5b691843f:~# ./process_image.sh imgs/bikes.jpg
Processing imgs/bikes.jpg
WARNING:tensorflow:From /root/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/ops/image_processing.py:95 in image_summary.: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
WARNING:tensorflow:From /root/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/ops/image_processing.py:95 in image_summary.: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
WARNING:tensorflow:From /root/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/ops/image_processing.py:95 in image_summary.: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
Captions for image bikes.jpg:
  0) a group of people riding bikes down a dirt road . (p=0.003389)
  1) a group of people riding bikes down a road . (p=0.001443)
  2) a group of people riding bikes down a trail . (p=0.000774)
```

**Comment by jmfu95** [comment]
I tried again and it worked.I see the prediction in the end.
Thank you so much.That's very kind of you!
